DROP SEQUENCE ALL_BOARDSEQ1;
DROP TABLE ALL_BOARD1;

CREATE SEQUENCE ALL_BOARDSEQ1;

CREATE TABLE ALL_BOARD1(
	ARTICLE_NO NUMBER PRIMARY KEY,
	BRD_NO NUMBER NOT NULL,
	MEM_NO NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL,
	HIT NUMBER,
	IMAGE VARCHAR2(4000)
	
);

--ARTICLE_NO, BRD_NO, MEM_NO, TITLE, CONTENT, REGDATE,HIT, IMAGE 

--BRD_NO : 1 공지 2 입양대기 3 입양후기 4 Q&A

INSERT INTO ALL_BOARD1
VALUES (ALL_BOARDSEQ1.NEXTVAL, 1, 3, '공지글시작', '공지글을 한번 작성해봤어요',SYSDATE, 1,NULL);

INSERT INTO ALL_BOARD1
VALUES (ALL_BOARDSEQ1.NEXTVAL, 2, 3, '입양대기글시작', '입양대기글을 한번 작성해봤어요',SYSDATE, 1,NULL);

INSERT INTO ALL_BOARD1
VALUES (ALL_BOARDSEQ1.NEXTVAL, 3, 3, '입양후기글시작', '입양후기글을 한번 작성해봤어요',SYSDATE, 1,NULL);

INSERT INTO ALL_BOARD1
VALUES (ALL_BOARDSEQ1.NEXTVAL, 4, 3, '질문글시작', '질문글을 한번 작성해봤어요',SYSDATE, 1,NULL);



SELECT * FROM ALL_BOARD1
ORDER BY ARTICLE_NO DESC;