DROP SEQUENCE BOARD1;
DROP TABLE BOARD1;

CREATE SEQUENCE BOARDSEQ1;

CREATE TABLE BOARD1(
	BRD_NO NUMBER NOT NULL,
	BOARDNAME VARCHAR(400) NOT NULL
);

INSERT INTO BOARD1
VALUES (5, 'QNA 게시판');

SELECT * FROM BOARD1
ORDER BY BRD_NO;
