/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-04-06 05:50:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dto.LoginDto;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.net.URLEncoder;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.security.SecureRandom");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("com.dto.LoginDto");
    _jspx_imports_classes.add("java.math.BigInteger");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"google-signin-scope\" content=\"profile email\">\r\n");
      out.write("\t<meta name=\"google-signin-client_id\" content=\"393709466900-djrtjsb8etgtriiljfdqd58gp07vf6iu.apps.googleusercontent.com\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 제이쿼리 -->\r\n");
      out.write("    <script type=\"text/javascript\"src=\"https://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\t<!-- 카카오 -->\r\n");
      out.write("\t<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("\t<!-- 네이버 -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\t<!-- 구글 -->\r\n");
      out.write("\t<!-- <script src=\"https://apis.google.com/js/platform.js\" async defer></script> -->\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Roboto\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  \t<script src=\"https://apis.google.com/js/api:client.js\"></script>\r\n");
      out.write("  \t\r\n");
      out.write("  \t<!-- GOOGLE LOGIN -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t  var googleUser = {};\r\n");
      out.write("\t  var startApp = function() {\r\n");
      out.write("\t    gapi.load('auth2', function(){\r\n");
      out.write("\t      \r\n");
      out.write("\t      auth2 = gapi.auth2.init({\r\n");
      out.write("\t        client_id: '393709466900-djrtjsb8etgtriiljfdqd58gp07vf6iu.apps.googleusercontent.com',\r\n");
      out.write("\t        cookiepolicy: 'single_host_origin',\r\n");
      out.write("\t        // Request scopes in addition to 'profile' and 'email'\r\n");
      out.write("\t        scope: 'profile email'\r\n");
      out.write("\t      });\r\n");
      out.write("\t      \r\n");
      out.write("\t      attachSignin(document.getElementById('customBtn'));\r\n");
      out.write("\t    });\r\n");
      out.write("\t  };\r\n");
      out.write("\t\r\n");
      out.write("\t  function attachSignin(element) {\r\n");
      out.write("\t    console.log(element.id);\r\n");
      out.write("\t    auth2.attachClickHandler(element, {},\r\n");
      out.write("\t        function(googleUser) {\r\n");
      out.write("\t          location.href=\"sns.do?command=googlelogin&google_email=\"+googleUser.getBasicProfile().getEmail() + \"&google_name=\"+googleUser.getBasicProfile().getName();\r\n");
      out.write("\t        }, function(error) {\r\n");
      out.write("\t          alert(JSON.stringify(error, undefined, 2));\r\n");
      out.write("\t        });\r\n");
      out.write("\t  }\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("    #customBtn {\r\n");
      out.write("      margin-left: 10px;\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      background: white;\r\n");
      out.write("      color: #444;\r\n");
      out.write("      width: 100px;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      box-shadow: 1px 1px 1px grey;\r\n");
      out.write("      white-space: nowrap;\r\n");
      out.write("    }\r\n");
      out.write("    #customBtn:hover {\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    span.label {\r\n");
      out.write("      font-family: serif;\r\n");
      out.write("      font-weight: normal;\r\n");
      out.write("    }\r\n");
      out.write("    span.icon {\r\n");
      out.write("      background: url('resources/LoginImage/g-normal.png') transparent 5px 50% no-repeat;\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      vertical-align: middle;\r\n");
      out.write("      width: 36px;\r\n");
      out.write("      height: 36px;\r\n");
      out.write("    }\r\n");
      out.write("    span.buttonText {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      vertical-align: middle;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      /* Use the Roboto font that is loaded in the <head> */\r\n");
      out.write("      font-family: 'Roboto', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\t<!-- login css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/loginpage.css\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("    function idCheckProc() {\r\n");
      out.write("        var chk = document.getElementsByName (\"mem_id\")[1].title;\r\n");
      out.write("        if(chk == 'n'){\r\n");
      out.write("            alert(\"id 중복체크를 해주세요!\");\r\n");
      out.write("            document.getElementsByName(\"mem_id\")[1].focus();\r\n");
      out.write("        \t}\r\n");
      out.write("   \t}\r\n");
      out.write("    \r\n");
      out.write("    function idCheck(){\r\n");
      out.write("        var mem_id = document.getElementsByName(\"mem_id\")[1].value; \r\n");
      out.write("        //팝업창 가운데 정렬\r\n");
      out.write("        var screenW = screen.availWidth; // 스크린 가로사이즈\r\n");
      out.write("        var screenH = screen.availHeight; // 스크린 세로사이즈\r\n");
      out.write("        var popW =300; //팝업창 가로사이즈\r\n");
      out.write("        var popH =200; //팝업창 세로사이즈\r\n");
      out.write("        var posL=(screenW-popW)/2; //팝업창 가로 포지션\r\n");
      out.write("        var posT=(screenH-popH)/2; //팝업창 세로 포지션\r\n");
      out.write("        \r\n");
      out.write("        if(mem_id==null|| mem_id.trim() == \"\"){\r\n");
      out.write("            alert(\"id를 입력해 주세요 !\");\r\n");
      out.write("        }else {\r\n");
      out.write("            open('login.do?command=idchk&mem_id='+mem_id,'test','width='+popW+',height='+popH+',top='+posT+',left='+posL+',resizable=no,scrolbars=no');\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function goPopup() {\r\n");
      out.write("    \t// 주소검색을 수행할 팝업 페이지를 호출합니다.\r\n");
      out.write("    \t// 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(https://www.juso.go.kr/addrlink/addrLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("    \tvar pop = window.open(\"jusoPopup.jsp\", \"pop\",\r\n");
      out.write("    \t\t\t\"width=570,height=420, scrollbars=yes, resizable=yes\");\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function jusoCallBack(roadFullAddr) {\r\n");
      out.write("    \tvar addressEl = document.querySelector(\"#address\");\r\n");
      out.write("    \taddressEl.value = roadFullAddr;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function toggleForm(){\r\n");
      out.write("        container = document.querySelector('.container');\r\n");
      out.write("        section = document.querySelector('section');\r\n");
      out.write("\r\n");
      out.write("        container.classList.toggle('active');\r\n");
      out.write("        section.classList.toggle('active');\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

	LoginDto logindto;
	String email = "";
	String name = "";
	if(request.getAttribute("loginDto")!=null ){
		logindto = (LoginDto) request.getAttribute("loginDto");
		if(logindto.getMem_name() != null){
			name = logindto.getMem_name();
		}		
		email = logindto.getMem_email();
	
      out.write("\r\n");
      out.write("\t\twindow.onload = function(){\r\n");
      out.write("\t\t\ttoggleForm();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \t</script>\r\n");
      out.write("\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body> \r\n");
      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("    <!-- 로그인 부분 -->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"user signinBx\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"imgBx\">\r\n");
      out.write("                    <img src=\"resources/img/dog_login.jpg\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"formBx\">\r\n");
      out.write("                    <form action=\"login.do\" method=\"post\">\r\n");
      out.write("                    \t<input type=\"hidden\" name=\"command\" value=\"login\">\r\n");
      out.write("                        <h2>로그인</h2>\r\n");
      out.write("                        <input type=\"text\" placeholder=\"Username\" name=\"mem_id\">\r\n");
      out.write("                        <input type=\"password\" placeholder=\"PassWord\" name=\"mem_pw\">\r\n");
      out.write("                        <input type=\"submit\" value=\"Login\">\r\n");
      out.write("                        <input class=\"homeBtn\" type=\"button\" value=\"Main\" onclick=\"location.href='index.jsp'\">\r\n");
      out.write("                        <p class=\"signup\"> 아이디가 없으신가요? <a onclick=\"toggleForm();\">회원가입</a></p>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"SNSButton\">\r\n");
      out.write("                        \t<!-- 카카오 버튼 -->\r\n");
      out.write("\t\t\t\t\t\t\t<a id=\"kakao-login-btn\" style=\"display:none;\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"kakao\" onclick=\"document.getElementById('kakao-login-btn').click();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"\" src=\"resources/LoginImage/kakao.png\" width=\"72\" height=\"36\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 네이버 버튼 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"naver_id_login\" class=\"SNSbuttons\"></div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 구글 버튼 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"gSignInWrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t   <div id=\"customBtn\" class=\"customGPlusSignIn\">\r\n");
      out.write("\t\t\t\t\t\t\t     <span class=\"icon\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t     <span class=\"buttonText\">Google</span>\r\n");
      out.write("\t\t\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t\t<script>startApp();</script>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"g-signin2 SNSbuttons\" data-onsuccess=\"onSignIn\" heigth=\"50\"></div>\t -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t<!-- 회원가입 부분 -->\r\n");
      out.write("            <div class=\"user signupBx\">\r\n");
      out.write("                <div class=\"formBx\">\r\n");
      out.write("                    <form action=\"login.do\" method=\"post\">\r\n");
      out.write("                    \t<input type=\"hidden\" name=\"command\" value=\"insertuser\">\r\n");
      out.write("                        <h2>회원가입</h2>\r\n");
      out.write("                        <div>\r\n");
      out.write("                        \t<input type=\"text\" name=\"mem_id\" required=\"required\" title=\"n\" placeholder=\"ID\"><input type=\"button\" value=\"중복확인\" onclick=\"idCheck();\" class=\"checkButton\">\r\n");
      out.write("                       \t</div>                      \r\n");
      out.write("                        <input type=\"password\" placeholder=\"Create Password\" name=\"mem_pw\" required=\"required\" onclick=\"idCheckProc();\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"Username\" name=\"mem_name\" required=\"required\" onclick=\"idCheckProc()\" value=\"");
      out.print(name );
      out.write("\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"Nickname\" name=\"mem_nickname\" required=\"required\" onclick=\"idCheckProc()\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"PhoneNumber\" name=\"mem_phone\" required=\"required\" onclick=\"idCheckProc()\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                        \t<input type=\"text\" name=\"mem_addr\" id=\"address\" class=\"form-control\" placeholder=\"도로명 주소를 입력해 주세요\" required readonly><input type=\"button\" class=\"btn btn-info checkButton\" onClick=\"goPopup();\" value=\"검색\">\r\n");
      out.write("                        </div>       \r\n");
      out.write("                        <input type=\"text\" placeholder=\"Email\" name=\"mem_email\" required=\"required\" onclick=\"idCheckProc()\" value=\"");
      out.print(email );
      out.write("\">\r\n");
      out.write("                        <input type=\"submit\" value=\"Sign up\">\r\n");
      out.write("                        <p class=\"signup\"> 아이디가 있으신가요? <a onclick=\"toggleForm();\">로그인</a></p>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"imgBx\">\r\n");
      out.write("                    <img src=\"resources/img/cat_login.jpg\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t<!-- KAKAO LOGIN -->\t\t\r\n");
      out.write("     <script type=\"text/javascript\">\r\n");
      out.write("\t\tKakao.init('90c04b9f0318b89033c0670c0eec9a87');\r\n");
      out.write("\r\n");
      out.write("\t\tKakao.Auth.createLoginButton({\r\n");
      out.write("\t\t\t//id값을 설정한 곳에 버튼을 자동생성한다\r\n");
      out.write("\t\t\tcontainer : '#kakao-login-btn',\r\n");
      out.write("\t\t\tsuccess : function(authObj) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//request함수를 통해 사용자 정보를 얻는다\r\n");
      out.write("\t\t\t\tKakao.API.request({\r\n");
      out.write("\t\t\t\t\turl : '/v2/user/me',\r\n");
      out.write("\t\t\t\t\tsuccess : function(res) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tlocation.href=\"sns.do?command=kakaologin&kakao_email=\"+res.kakao_account.email+\"\";\r\n");
      out.write("\t\t\t\t\t\t//window.close();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tconsole.log(authObj);\r\n");
      out.write("\t\t\t\tvar token = authObj.access_token;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfail : function(err) {\r\n");
      out.write("\t\t\t\talert(JSON.stringify(err));\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- NAVER -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 네이버아이디로로그인 버튼 노출 영역 -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("  \t\tvar naver_id_login = new naver_id_login(\"JKUnL3XzuIStyOJXkUaH\", \"http://localhost:8787/Semi/login_callback.jsp\");\r\n");
      out.write("  \t\tvar state = naver_id_login.getUniqState();\r\n");
      out.write("\t  \tnaver_id_login.setButton(\"green\", 2,36); // 새성된 버튼 색깔 green 3번 옵션으로 넣어줌 \r\n");
      out.write("\t  \tnaver_id_login.setDomain(\"http://localhost:8787\"); // service url 넣어줌 \r\n");
      out.write("\t \tnaver_id_login.setState(state);\r\n");
      out.write("\t\tnaver_id_login.setPopup(); // 팝업 설정\r\n");
      out.write("\t\tnaver_id_login.init_naver_id_login();\r\n");
      out.write("  \t</script>\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
