/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-04-05 15:02:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dto.PagingDto;
import com.biz.LoginBiz;
import com.dto.BoardDto;
import com.dto.SemiDto;
import java.util.List;
import com.dto.LoginDto;

public final class noticeboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1614137368486L));
    _jspx_dependants.put("jar:file:/C:/Users/kas78/Desktop/khkhkh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/Form/header.jsp", Long.valueOf(1617545595814L));
    _jspx_dependants.put("jar:file:/C:/Users/kas78/Desktop/khkhkh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/kas78/Desktop/khkhkh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dto.PagingDto");
    _jspx_imports_classes.add("com.dto.LoginDto");
    _jspx_imports_classes.add("com.biz.LoginBiz");
    _jspx_imports_classes.add("com.dto.SemiDto");
    _jspx_imports_classes.add("com.dto.BoardDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<style>\r\n");
      out.write(".btn:focus, .btn:active, .btn:hover, input:active, input:focus, nav:active,\r\n");
      out.write("\tnav:focus, nav:hover {\r\n");
      out.write("\tbox-shadow: none !important;\r\n");
      out.write("\toutline: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#notice_list a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("    <!-- CSS only -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("    \r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Notice Board List</title>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	List<BoardDto> list = (List<BoardDto>) request.getAttribute("list");
	int pageNum = request.getParameter("page") == null ? 1 : Integer.parseInt(request.getParameter("page"));
	int totalCount = Integer.parseInt(request.getAttribute("totalCount") + "");

	PagingDto paging = new PagingDto();
	paging.setPageNo(pageNum);
	paging.setPageSize(10);
	paging.setTotalCount(totalCount);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar pageNum = ");
      out.print(pageNum - 1);
      out.write(";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(pageNum >= 10){\r\n");
      out.write("\t\t\t\tpageNum %= 10;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\".pagination>a\").eq(pageNum).addClass(\"on\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("  <!-- 헤더부분 추가 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" \r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"resources/js/header.js\"></script>\r\n");
      out.write("\t<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" />\r\n");
      out.write("\t<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resouces/bootstrap/js/bootstrap.js\"></script>-->\r\n");
      out.write("</head>\r\n");
      out.write("  <body>\r\n");
      out.write("  ");

  	LoginDto dto1 = (LoginDto)session.getAttribute("dto");
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <header>\r\n");
      out.write("\t      <!-- 로고 부분 -->\r\n");
      out.write("\t      <a href=\"move.do?move=home\" class=\"brand\">\r\n");
      out.write("\t      \t<img src=\"resources/img/logo.png\" alt=\"\" width=\"200px\">\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t      <!-- ? -->\r\n");
      out.write("\t      <div class=\"menu-btn\"></div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <!-- 항복 부분 -->\r\n");
      out.write("\t      <div class=\"navigation\">\r\n");
      out.write("\t      \t<a href=\"move.do?move=petboard\">펫보드</a>\r\n");
      out.write("\t        <a href=\"move.do?move=noticeboard\">공지사항</a>\r\n");
      out.write("\t        <a href=\"move.do?move=matchPet\">얼굴인식</a>\r\n");
      out.write("\t        <a href=\"move.do?move=donation\">기부페이지</a>\r\n");
      out.write("\t        <a href=\"move.do?move=map\">지도페이지이동</a>\r\n");
      out.write("\t        <a href=\"move.do?move=doctor\">펫닥터페이지</a>\r\n");
      out.write("\t        ");

			if( dto1 != null ){
				if(dto1.getMem_image() == null){			    	
			
      out.write("\r\n");
      out.write("\t\t\t<div style=\"display : inline;\">\r\n");
      out.write("\t\t\t\t<a href=\"mypage.jsp\">\r\n");
      out.write("\t        \t\t<img src=\"resources/img/profile.jpg\"  width=\"32px\" height=\"32px;\" style=\"border-radius: 50%; overflow: hidden;\" >\r\n");
      out.write("\t        \t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t        \t\t\t\t\t    \t\t\r\n");
      out.write("\t\t\t");

			    }else{
			
      out.write("\r\n");
      out.write("\t       \t<a href=\"mypage.jsp\">\r\n");
      out.write("\t            <img src=\"./upload/");
      out.print(dto1.getMem_image() );
      out.write("\"  width=\"32px\" height=\"32px;\" style=\"border-radius: 50%; overflow: hidden;\">\r\n");
      out.write("\t        </a>\r\n");
      out.write("\t\t\t");

				}			
			
      out.write("\r\n");
      out.write("\t\t   \t<a href=\"login.do?command=logout\">\r\n");
      out.write("\t\t   \t\t<button>로그아웃</button>\r\n");
      out.write("\t\t   \t</a>\r\n");
      out.write("\t       \t");

	       	} else {
	      	
      out.write("\r\n");
      out.write("\t       \t<a href=\"move.do?move=loginpage\">\r\n");
      out.write("\t       \t\t<button>로그인</button> \r\n");
      out.write("\t       \t</a>\r\n");
      out.write("\t       \t");

	       	}
	       	
      out.write("\r\n");
      out.write("\t       \t</div> \r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"upsite\"></div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 바디부분 시작 -->\r\n");
      out.write("    <div class=\"mt-4\">\r\n");
      out.write("      <div class=\"container d-flex justify-content-center\"><!-- 가로 폭 조절 -->\r\n");
      out.write("        <div class=\"col-99\">\r\n");
      out.write("        <div class=\"card\"><!-- 카드 시작 -->\r\n");
      out.write("        <div class=\"noticeboard_list\">\r\n");
      out.write("    \r\n");


	


      out.write("    \r\n");
      out.write("    <h2 style=\"margin-bottom: 20px; margin-top: 20px; text-align: center\">공지사항</h2>\r\n");
      out.write("    <table class=\"table table-hover\" id=\"list\">\r\n");
      out.write("    \t<col width=\"70px\"/>\r\n");
      out.write("    \t<col width=\"500px\"/>\r\n");
      out.write("    \t<col width=\"120px\"/>\r\n");
      out.write("    \t<col width=\"120px\"/>\r\n");
      out.write("    \t<col width=\"70px\"/>\r\n");
      out.write("    <thead>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"col\" class=\"\" style=\"text-align: center;\">번호</th>\r\n");
      out.write("\t\t\t<th scope=\"col\" class=\"\">제목</th>\r\n");
      out.write("\t\t\t<th scope=\"col\" class=\"\" style=\"text-align: center;\">작성자</th>\r\n");
      out.write("\t\t\t<th scope=\"col\" class=\"\" style=\"text-align: center;\">날짜</th>\r\n");
      out.write("\t\t\t<th scope=\"col\" class=\"\" style=\"text-align: center;\">조회수</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</thead>\r\n");
      out.write("\r\n");

	if(list == null || list.size() ==0){

      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"4\">----글 없음-----</td>\r\n");
      out.write("\t\t</tr>\r\n");

	} else {
		
		
		//getBrd_no() ==1 : 공지글만 보기
		for (BoardDto dto : list){
			

      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("    \t\t<td style=\"text-align: center;\">");
      out.print(dto.getArticle_no());
      out.write("</td>\r\n");
      out.write("    \t\t<td><a href=\"notice.do?command=selectone&article_no=");
      out.print(dto.getArticle_no() );
      out.write("\" style=\"text-decoration: none; color:black;\">");
      out.print( dto.getTitle());
      out.write("</a></td>\r\n");
      out.write("    \t\t<td style=\"text-align: center;\">");
      out.print( dto.getMem_name() );
      out.write("</td>\r\n");
      out.write("    \t\t<td style=\"text-align: center;\">");
      out.print( dto.getRegdate());
      out.write("</td>\r\n");
      out.write("    \t\t<td style=\"text-align: center;\">");
      out.print( dto.getHit() );
      out.write("</td>\r\n");
      out.write("    \t</tr>\r\n");

		}
	}
	
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"text-align: right; margin-right: 10px; margin-bottom: 10px;\">\r\n");
      out.write("    <input type=\"button\" class=\"btn btn-primary\" value=\"글작성\" onclick=\"location.href='notice.do?command=insertform'\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("       <!-- pagination-->\r\n");
      out.write("\t<div class=\"pagination\">\r\n");
      out.write("\t\t<input type=\"button\" onclick=\"pageMove(");
      out.print(paging.getFirstPageNo());
      out.write(")\"\r\n");
      out.write("\t\t\tvalue=\"◀\"> <input type=\"button\"\r\n");
      out.write("\t\t\tonclick=\"pageMove(");
      out.print(paging.getPrevPageNo());
      out.write(")\" value=\"◁\">\r\n");
      out.write("\r\n");
      out.write("\t\t");

			for (int i = paging.getStartPageNo(); i <= paging.getEndPageNo(); i++) {
		
      out.write("\r\n");
      out.write("\t\t<a onclick=\"pageMove(");
      out.print(i);
      out.write(')');
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"button\" onclick=\"pageMove(");
      out.print(paging.getNextPageNo());
      out.write(")\"\r\n");
      out.write("\t\t\tvalue=\"▷\"> <input type=\"button\"\r\n");
      out.write("\t\t\tonclick=\"pageMove(");
      out.print(paging.getFinalPageNo());
      out.write(")\" value=\"▶\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\tfunction pageMove(page){\r\n");
      out.write("\t\t\t\tlocation.href='notice.do?command=list&page='+page\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t <!-- pagination 끝-->\r\n");
      out.write("\t\r\n");
      out.write("    </div><!-- 카드 끝 -->\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
