/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-04-01 10:49:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dto.LoginDto;

public final class petboard_005fadopt_005fchecklist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Form/header.jsp", Long.valueOf(1617252940769L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dto.LoginDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tbox-shadow: none !important;\r\n");
      out.write("\toutline: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("    <!-- CSS only -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("<title>Checklist</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" \r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("\t<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" />\r\n");
      out.write("\t<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resouces/bootstrap/js/bootstrap.js\"></script>-->\r\n");
      out.write("</head>\r\n");
      out.write("  <body>\r\n");
      out.write("  ");

  	LoginDto dto1 = (LoginDto)session.getAttribute("dto");
  	System.out.println("session 담겼을을까요?" + dto1);	
  
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("      <!-- 네비게이션바 -->\r\n");
      out.write("      <nav class=\"navbar navbar-expend-lg navbar-light bg-light\">\r\n");
      out.write("        <div class=\"container justify-content-center\">\r\n");
      out.write("          <div class=\"d-flex flex-row justify-content-between align-items-center col-9\">\r\n");
      out.write("            <!-- 로고 -->\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"move.do?move=home\">\r\n");
      out.write("              <img src=\"resources/img/logo.png\" alt=\"\" width=\"200px\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <!-- 서칭박스 -->\r\n");
      out.write("            <div>\r\n");
      out.write("              <form class=\"d-flex\">\r\n");
      out.write("                <input class=\"form-control me-2\" type=\"search\" placeholder=\"검색\" aria-label=\"Search\" size=\"45\" >\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 아이콘 리스트 -->\r\n");
      out.write("            <div>\r\n");
      out.write("              <ul class=\"list-inline m-0\">\r\n");
      out.write("              <!-- 공지사항  -->\r\n");
      out.write("                <li class=\"list-inline-item ms-2\">\r\n");
      out.write("                <a href=\"move.do?move=noticeboard\" class=\"link-menu\">\r\n");
      out.write("                  <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\" class=\"bi bi-info-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("  \t\t\t\t\t<path d=\"M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z\"/>\r\n");
      out.write("  \t\t\t\t\t<path d=\"M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z\"/>\r\n");
      out.write("\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("                </li>\r\n");
      out.write("              <!-- 동물 얼굴인식 -->\r\n");
      out.write("                <li class=\"list-inline-item ms-2\">\r\n");
      out.write("                  <a href=\"move.do?move=matchPet\" class=\"link-menu\">\r\n");
      out.write("                    <svg id=\"Capa_1\" enable-background=\"new 0 0 512 512\" height=\"24\" viewBox=\"0 0 512 512\" width=\"24\" xmlns=\"http://www.w3.org/2000/svg\"><g><path d=\"m382.749 195.774-25.182-17.168 1.756 30.426c2.164 37.49-20.201 64.829-34.271 71.342-11.347-6.83-24.356-10.407-38.052-10.407h-61c-24.935 0-46-20.607-46-45v-60c0-24.813-20.187-45-45-45h-45c-33.084 0-60 26.916-60 60h-30v45c0 36.219 25.809 66.524 60 73.493v34.208c0 28.702 10.864 56.872 30 78.261v101.038h90v-92h69.787l4.394 4.394c12.796 12.796 29.688 21.301 47.819 24.352v63.255h90v-110.542l-24.416-48.832c33.97-14.691 54.416-47.481 54.416-82.627 0-29.7-14.674-57.436-39.251-74.193zm-262.749-45.807h15c8.271 0 15 6.729 15 15v30c0 8.271-6.729 15-15 15s-15-6.729-15-15zm223.936 178.817-11.936 2.491v17.233l30 60v73.459h-30v-62h-15c-15.521 0-31.074-6.288-41.606-16.819l-13.18-13.181h-112.214v92h-30v-83.213c-1.293-1.86-30-24.315-30-66.086v-62.701h-15c-24.813 0-45-20.187-45-45v-15h30v-30c0-16.542 13.458-30 30-30v45c0 24.813 20.187 45 45 45 5.634 0 11.025-1.05 16-2.95 2.551 15.471 9.984 29.761 21.588 41.103 14.413 14.088 33.381 21.847 53.412 21.847h61c18.801 0 28.424 10.744 31.223 12.354 2.148-.853 28.406 1.371 52.382-35.246 6.819-10.415 11.886-21.919 15.04-33.917 4.121 8.201 6.355 17.355 6.355 26.809 0 28.725-19.765 52.911-48.064 58.817z\"/><path d=\"m113.463 45.253h30v60h-30z\" transform=\"matrix(.996 -.087 .087 .996 -6.07 11.483)\"/><path d=\"m194.714 143.431h60v30h-60z\" transform=\"matrix(.996 -.087 .087 .996 -12.953 20.189)\"/><path d=\"m168.209 77.514h60v30h-60z\" transform=\"matrix(.643 -.766 .766 .643 -.068 184.882)\"/><path d=\"m467 117.967c-11.328 0-21.684 4.217-29.603 11.151l-219.801-129.085-15.192 25.869 220.27 129.36c-.434 2.506-.674 5.077-.674 7.705 0 24.813 20.187 45 45 45s45-20.187 45-45-20.187-45-45-45zm0 60c-8.271 0-15-6.729-15-15s6.729-15 15-15 15 6.729 15 15-6.729 15-15 15z\"/></g></svg>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("               <!--기부페이지 -->\r\n");
      out.write("                <li class=\"list-inline-item ms-2\">\r\n");
      out.write("                  <a href=\"move.do?move=donation\" class=\"link-menu\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\" class=\"bi bi-suit-heart\" viewBox=\"0 0 16 16\">\r\n");
      out.write(" \t\t\t\t\t <path d=\"M8 6.236l-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z\"/>\r\n");
      out.write("\t\t\t\t\t</svg>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("               <!-- 지도페이지 이동 -->\r\n");
      out.write("                <li class=\"list-inline-item ms-2\">\r\n");
      out.write("                  <a href=\"move.do?move=map\" class=\"link-menu\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\" class=\"bi bi-map\" viewBox=\"0 0 16 16\">\r\n");
      out.write("  \t\t\t\t\t <path fill-rule=\"evenodd\" d=\"M15.817.113A.5.5 0 0 1 16 .5v14a.5.5 0 0 1-.402.49l-5 1a.502.502 0 0 1-.196 0L5.5 15.01l-4.902.98A.5.5 0 0 1 0 15.5v-14a.5.5 0 0 1 .402-.49l5-1a.5.5 0 0 1 .196 0L10.5.99l4.902-.98a.5.5 0 0 1 .415.103zM10 1.91l-4-.8v12.98l4 .8V1.91zm1 12.98l4-.8V1.11l-4 .8v12.98zm-6-.8V1.11l-4 .8v12.98l4-.8z\"/>\r\n");
      out.write("\t\t\t\t\t</svg>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("               <!-- 펫닥터 페이지  -->\r\n");
      out.write("                <li class=\"list-inline-item ms-2\">\r\n");
      out.write("                  <a href=\"move.do?move=doctor\" class=\"link-menu\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\" class=\"bi bi-border-all\" viewBox=\"0 0 16 16\">\r\n");
      out.write("  \t\t\t\t\t\t<path d=\"M0 0h16v16H0V0zm1 1v6.5h6.5V1H1zm7.5 0v6.5H15V1H8.5zM15 8.5H8.5V15H15V8.5zM7.5 15V8.5H1V15h6.5z\"/>\r\n");
      out.write("\t\t\t\t\t</svg>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("               <!-- 회원 정보 -->\r\n");
      out.write("               ");

               		if( dto1 != null ){
               
      out.write("\r\n");
      out.write("                <li class=\"list-inline-item align-middle ms-2\">\r\n");
      out.write("                  <a href=\"#\">\r\n");
      out.write("                    <div class=\"rounded-circle overflow-hidden d-flex justify-content-center align-items-center topbar-profile-photo\" >\r\n");
      out.write("                      <img src=\"resources/img/profile.jpg\" alt=\"\" style=\"transform: scale(1.5); width: 100%; position: absolute; left: 0;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!--로그아웃-->\r\n");
      out.write("                <li class=\"list-inline-item align-middle ms-2\">\r\n");
      out.write("               \t  <a href=\"login.do?command=logout\">\r\n");
      out.write("               \t\t<div>\r\n");
      out.write("               \t\t\t<button class=\"btn btn-danger\" >로그아웃</button>\r\n");
      out.write("               \t\t</div>\r\n");
      out.write("               \t  </a>\r\n");
      out.write("               \t</li>\r\n");
      out.write("               ");

               		} else {
               
      out.write("\r\n");
      out.write("               \t<li class=\"list-inline-item align-middle ms-2\">\r\n");
      out.write("               \t  <a href=\"move.do?move=loginpage\">\r\n");
      out.write("               \t\t<div>\r\n");
      out.write("               \t\t\t<button class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("               \t\t</div>\r\n");
      out.write("               \t  </a>\r\n");
      out.write("               \t</li>\r\n");
      out.write("               ");

               		}
               
      out.write(" \r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mt-4\">\r\n");
      out.write("\t\t<div class=\"container d-flex justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"col-9\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("    \t<h2 style=\"margin-bottom: 20px; margin-top: 20px; text-align: center\">입양 신청 전 CHECK LIST</h2>\r\n");
      out.write("    \t\t\t\t<div class=\"check_start\" style=\"margin-left: 20%;\"><!-- 체크 항목 시작 -->\r\n");
      out.write("    \t\t\t<form>\r\n");
      out.write("\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t    <label for=\"friendname\" class=\"form-label\">1. 입양을 희망하는 아이 이름</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"friendname\"></div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t    <label for=\"age\" class=\"form-label\">2. 통화하기 편한 시간</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"age\"></div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t    <label for=\"adr\" class=\"form-label\">3. 거주지</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"adr\" placeholder=\"(예: 서울, 경기, 강원... 등)\"></div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t    <label for=\"marriage\" class=\"form-label\">4. 결혼 여부</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t    <div class=\"form-check\">\r\n");
      out.write("\t\t\t\t    \t<input class=\"form-check-input\" type=\"radio\" name=\"marriage\" id=\"marriage\">\r\n");
      out.write("\t\t\t\t\t\t  <label class=\"form-check-label\" for=\"marriage\">\r\n");
      out.write("\t\t\t\t\t\t    미혼\r\n");
      out.write("\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t  <input class=\"form-check-input\" type=\"radio\" name=\"marriage\" id=\"marriage\" checked>\r\n");
      out.write("\t\t\t\t\t\t  <label class=\"form-check-label\" for=\"marriage\">\r\n");
      out.write("\t\t\t\t\t\t    기혼\r\n");
      out.write("\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t   \t</div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t    <label for=\"job\" class=\"form-label\">5. 신청인 직업</label>\r\n");
      out.write("\t\t\t\t\t    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"job\"></div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t  \t<label for=\"pet\" class=\"form-label\">6. 예전에 반려동물을 키우신 적이 있나요?</label>\r\n");
      out.write("\t\t\t\t\t  \t<div id=\"pet\" class=\"form-text\">만약 있으시다면 어떤 종류의 동물인지, 지금은 어떻게 되었는지 기재해 주세요</div>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"Q1\" rows=\"3\" class=\"form-control form-control-md rounded-0\"></textarea></div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t  \t<label for=\"pet2\" class=\"form-label\">7. 현재 키우는 반려동물이 있나요?</label>\r\n");
      out.write("\t\t\t\t\t  \t<div id=\"pet2\" class=\"form-text\">만약 있으시다면 종류와 나이, 성별, 중성화 여부 등 특징을 기재해 주세요</div>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"Q2\" rows=\"3\" class=\"form-control form-control-md rounded-0\"></textarea></div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t  \t<label for=\"live\" class=\"form-label\">8. 현재 거주하고 계신 주택 형태와 가족 구성원은 어떻게 되나요?</label>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"Q3\" rows=\"3\" class=\"form-control form-control-md rounded-0\"></textarea></div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t  \t<label for=\"why\" class=\"form-label\">9. 입양을 원하시는 이유는 무엇인가요?</label>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"Q4\" rows=\"3\" class=\"form-control form-control-md rounded-0\"></textarea></div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  <div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t    <label for=\"baby\" class=\"form-label\">10. 만약 댁에서 새로운 아기가 출생할 경우 입양된 동물을 계속 키우실 수 있나요?</label>\r\n");
      out.write("\t\t\t\t    <div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t    <div class=\"form-check\">\r\n");
      out.write("\t\t\t\t    \t<input class=\"form-check-input\" type=\"radio\" name=\"babyradio\" id=\"babyradio\">\r\n");
      out.write("\t\t\t\t\t\t  <label class=\"form-check-label\" for=\"babyradio\">\r\n");
      out.write("\t\t\t\t\t\t    예\r\n");
      out.write("\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check\">\r\n");
      out.write("\t\t\t\t\t\t  <input class=\"form-check-input\" type=\"radio\" name=\"babyradio\" id=\"babyradio\" checked>\r\n");
      out.write("\t\t\t\t\t\t  <label class=\"form-check-label\" for=\"babyradio\">\r\n");
      out.write("\t\t\t\t\t\t    아니오\r\n");
      out.write("\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t\t   \t</div>\r\n");
      out.write("\t\t\t\t   \t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t\t  \t<label for=\"etc\" class=\"form-label\">11. 그 외에 입양 신청에 관해 덧붙이고자 하시는 말씀이 있으면 기재해 주세요</label>\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"Q5\" rows=\"3\" class=\"form-control form-control-md rounded-0\"></textarea></div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("   \t\t\t\t\t</div><!-- 체크 항목 끝 -->\r\n");
      out.write("   \t\t\t\t\t\r\n");
      out.write("   \t\t\t\t\t\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t\t    <div class=\"mt-3\" style=\"text-align: right; margin-right: 10px; margin-bottom: 10px;\">\r\n");
      out.write("    \t\t\t\t<input type=\"button\" class=\"btn btn-primary\" value=\"제출하기\" onclick=\"\"/>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
