/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-04-06 05:54:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import com.dto.LoginDto;

public final class petboard_005finsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1614137368486L));
    _jspx_dependants.put("/Form/header.jsp", Long.valueOf(1617642818132L));
    _jspx_dependants.put("jar:file:/C:/Users/kas78/Desktop/khkhkh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("com.dto.LoginDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("\t<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.btn {\r\n");
      out.write("\t\t\tbackground-color: #ff9999\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.btn:hover, .btn:focus {\r\n");
      out.write("\t\t\tbackground-color: hotpink\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.btn:focus, .btn:active, .btn:hover, input:active, input:focus {\r\n");
      out.write("\t\t\tbox-shadow: none !important;\r\n");
      out.write("\t\t\toutline: none !important;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<!-- 썸머노트 부트스트랩 파일 CDN -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\" integrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js\"></script>\r\n");
      out.write("\t<title>petBoard Insert</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"resources/js/header.js\"></script>\r\n");
      out.write("\t<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" />\r\n");
      out.write("\t<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resouces/bootstrap/js/bootstrap.js\"></script>-->\r\n");
      out.write("</head>\r\n");
      out.write("  <body>\r\n");
      out.write("  ");

  	LoginDto dto1 = (LoginDto)session.getAttribute("dto");
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <header>\r\n");
      out.write("\t      <!-- 로고 부분 -->\r\n");
      out.write("\t      <a href=\"move.do?move=home\" class=\"brand\">\r\n");
      out.write("\t      \t<img src=\"resources/img/logo.png\" alt=\"\" width=\"200px\">\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t      <!-- ? -->\r\n");
      out.write("\t      <div class=\"menu-btn\"></div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <!-- 항복 부분 -->\r\n");
      out.write("\t      <div class=\"navigation\">\r\n");
      out.write("\t      \t<a href=\"move.do?move=petboard\">펫보드</a>\r\n");
      out.write("\t        <a href=\"move.do?move=noticeboard\">공지사항</a>\r\n");
      out.write("\t        <a href=\"move.do?move=matchPet\">얼굴인식</a>\r\n");
      out.write("\t        <a href=\"move.do?move=donation\">기부페이지</a>\r\n");
      out.write("\t        <a href=\"move.do?move=map\">지도페이지이동</a>\r\n");
      out.write("\t        <a href=\"move.do?move=doctor\">펫닥터페이지</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

			if (dto1 != null) {
				if (dto1.getMem_image() == null) {
			
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"action1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"profile\" onclick=\"menuToggle()\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/img/profile.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<h7>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(dto1.getMem_name());
      out.write(" 님<br>\r\n");
      out.write("\t\t\t\t\t\t\t<span>환영합니다.</span>\r\n");
      out.write("\t\t\t\t\t\t</h7>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"resources/img/edit.png\" alt=\"\"><a href=\"login.do?command=updatform&mem_no=");
      out.print(dto1.getMem_no());
      out.write("\">Edit profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"resources/img/log-out.png\" alt=\"\"><a href=\"login.do?command=logout\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t        \t\t\t\t\t    \t\t\r\n");
      out.write("\t\t\t");

			    }else{
			
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"action1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"profile\" onclick=\"menuToggle()\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./upload/");
      out.print(dto1.getMem_image() );
      out.write("\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<h7>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(dto1.getMem_name());
      out.write(" 님<br>\r\n");
      out.write("\t\t\t\t\t\t\t<span>환영합니다.</span>\r\n");
      out.write("\t\t\t\t\t\t</h7>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"resources/img/edit.png\" alt=\"\"><a href=\"login.do?command=updatform&mem_no=");
      out.print(dto1.getMem_no());
      out.write("\">Edit profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"resources/img/log-out.png\" alt=\"\"><a href=\"login.do?command=logout\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");

				}			
       		} else {
	      	
      out.write("\r\n");
      out.write("\t       \t<a href=\"move.do?move=loginpage\">\r\n");
      out.write("\t       \t\t<button>로그인</button> \r\n");
      out.write("\t       \t</a>\r\n");
      out.write("\t       \t");

       		}
	       	
      out.write("\r\n");
      out.write("\t       \t</div> \r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"upsite\"></div>\r\n");
      out.write("  </body>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("\t  function menuToggle(){\r\n");
      out.write("\t      const toggleMenu = document.querySelector('.menu');\r\n");
      out.write("\t      toggleMenu.classList.toggle('active');\r\n");
      out.write("\t  }\r\n");
      out.write("  </script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 바디부분 시작 -->\r\n");
      out.write("\t<div class=\"mt-4\">\r\n");
      out.write("\t\t<div class=\"container d-flex justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"col-9\">\r\n");
      out.write("\t\t\t\t");
      com.dto.BoardDto dto = null;
      dto = (com.dto.BoardDto) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new com.dto.BoardDto();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					LoginDto logindto = (LoginDto) session.getAttribute("dto"); //컨트롤러에서 dto 받아와서 형변환 
					if (logindto == null) {
						PrintWriter script = response.getWriter();
						script.println("<script>");
						script.println("alert('로그인이 필요한 페이지입니다.')");
						script.println("location.href='login.jsp'");
						script.println("</script>");
					}	
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"pet.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"command\" value=\"insertres\" /> \r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"brd_no\" value=\"3\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"mem_no\" value=\"");
      out.print(logindto.getMem_no());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"image\" value=\"\" id=\"mainImage\"> \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"content-wrapper\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container justify-content-center\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"noticeboard\">\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"table\" id=\"sub_text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<col style=\"width: 100px\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<col style=\"width: *\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 style=\"margin-bottom: 20px; text-align: center\">입양 후기 작성</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"text-center\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"title\"\tname=\"title\" placeholder=\"제목을 입력해 주세요.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th class=\"text-center\">내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- 썸머노트 호출 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><textarea id=\"summernote\" name=\"content\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"text-align: right; margin-right: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn\" value=\"저장하기\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn\" value=\"목록으로\" onclick=\"location.href='petboard.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#summernote').summernote({\r\n");
      out.write("\t\t\theight : 700, // 에디터 높이\r\n");
      out.write("\t\t\tminHeight : 500, // 최소 높이\r\n");
      out.write("\t\t\tmaxHeight : 700, // 최대 높이\r\n");
      out.write("\t\t\tfocus : true, // 에디터 로딩후 포커스를 맞출지 여부\r\n");
      out.write("\t\t\tlang : \"ko-KR\", // 한글 설정\r\n");
      out.write("\t\t\tplaceholder : '글 내용을 입력해 주세요.', //placeholder 설정\r\n");
      out.write("\t\t\tcallbacks: {\r\n");
      out.write("\t\t\t    onImageUpload: function(files) {\r\n");
      out.write("\t\t            sendFile(files[0]);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction sendFile(file) {\r\n");
      out.write("\t\tvar form_data = new FormData();\r\n");
      out.write("\t       form_data.append('file', file);\r\n");
      out.write("\t       $.ajax({\r\n");
      out.write("\t         data: form_data,\r\n");
      out.write("\t         type: \"post\",\r\n");
      out.write("\t         url: './BoardFileInsert.do',\r\n");
      out.write("\t         cache: false,\r\n");
      out.write("\t         contentType: false,\r\n");
      out.write("\t         /* enctype: 'multipart/form-data', */\r\n");
      out.write("\t         processData: false,\r\n");
      out.write("\t         success: function(img_name) {\r\n");
      out.write("\t        \t console.log(img_name.url);\r\n");
      out.write("\t        \t var image = $('<img>').attr('src', img_name.url);\r\n");
      out.write("\t        \t console.log(image);\r\n");
      out.write("\t             $('#summernote').summernote(\"insertNode\", image[0])\r\n");
      out.write("\t             $('#mainImage').val(img_name.fileName);\r\n");
      out.write("\t         }\r\n");
      out.write("\t       });\r\n");
      out.write("\t    }\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
