/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-04-06 05:54:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.biz.BoardBiz;
import com.dto.BoardDto;
import com.dto.PetDto;
import java.util.List;
import com.dto.LoginDto;

public final class petboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1614137368486L));
    _jspx_dependants.put("/Form/header.jsp", Long.valueOf(1617642818132L));
    _jspx_dependants.put("jar:file:/C:/Users/kas78/Desktop/khkhkh/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dto.PetDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.dto.LoginDto");
    _jspx_imports_classes.add("com.biz.BoardBiz");
    _jspx_imports_classes.add("com.dto.BoardDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/petboard.css\" />\r\n");
      out.write("<script src=\"resources/js/petboard.js\"></script>  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	//로그인 세션 불러옵니다...
	LoginDto logindto = (LoginDto)session.getAttribute("dto");	

      out.write("\r\n");
      out.write("\r\n");

	// 리스트를 불러옵니다.
	List<BoardDto> list = (List<BoardDto>) request.getAttribute("list");

      out.write("  \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"resources/js/header.js\"></script>\r\n");
      out.write("\t<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" />\r\n");
      out.write("\t<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resouces/bootstrap/js/bootstrap.js\"></script>-->\r\n");
      out.write("</head>\r\n");
      out.write("  <body>\r\n");
      out.write("  ");

  	LoginDto dto1 = (LoginDto)session.getAttribute("dto");
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <header>\r\n");
      out.write("\t      <!-- 로고 부분 -->\r\n");
      out.write("\t      <a href=\"move.do?move=home\" class=\"brand\">\r\n");
      out.write("\t      \t<img src=\"resources/img/logo.png\" alt=\"\" width=\"200px\">\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t      <!-- ? -->\r\n");
      out.write("\t      <div class=\"menu-btn\"></div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <!-- 항복 부분 -->\r\n");
      out.write("\t      <div class=\"navigation\">\r\n");
      out.write("\t      \t<a href=\"move.do?move=petboard\">펫보드</a>\r\n");
      out.write("\t        <a href=\"move.do?move=noticeboard\">공지사항</a>\r\n");
      out.write("\t        <a href=\"move.do?move=matchPet\">얼굴인식</a>\r\n");
      out.write("\t        <a href=\"move.do?move=donation\">기부페이지</a>\r\n");
      out.write("\t        <a href=\"move.do?move=map\">지도페이지이동</a>\r\n");
      out.write("\t        <a href=\"move.do?move=doctor\">펫닥터페이지</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

			if (dto1 != null) {
				if (dto1.getMem_image() == null) {
			
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"action1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"profile\" onclick=\"menuToggle()\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/img/profile.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<h7>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(dto1.getMem_name());
      out.write(" 님<br>\r\n");
      out.write("\t\t\t\t\t\t\t<span>환영합니다.</span>\r\n");
      out.write("\t\t\t\t\t\t</h7>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"resources/img/edit.png\" alt=\"\"><a href=\"login.do?command=updatform&mem_no=");
      out.print(dto1.getMem_no());
      out.write("\">Edit profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"resources/img/log-out.png\" alt=\"\"><a href=\"login.do?command=logout\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t        \t\t\t\t\t    \t\t\r\n");
      out.write("\t\t\t");

			    }else{
			
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"action1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"profile\" onclick=\"menuToggle()\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./upload/");
      out.print(dto1.getMem_image() );
      out.write("\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<h7>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(dto1.getMem_name());
      out.write(" 님<br>\r\n");
      out.write("\t\t\t\t\t\t\t<span>환영합니다.</span>\r\n");
      out.write("\t\t\t\t\t\t</h7>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"resources/img/edit.png\" alt=\"\"><a href=\"login.do?command=updatform&mem_no=");
      out.print(dto1.getMem_no());
      out.write("\">Edit profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"resources/img/log-out.png\" alt=\"\"><a href=\"login.do?command=logout\">Logout</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");

				}			
       		} else {
	      	
      out.write("\r\n");
      out.write("\t       \t<a href=\"move.do?move=loginpage\">\r\n");
      out.write("\t       \t\t<button>로그인</button> \r\n");
      out.write("\t       \t</a>\r\n");
      out.write("\t       \t");

       		}
	       	
      out.write("\r\n");
      out.write("\t       \t</div> \r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"upsite\"></div>\r\n");
      out.write("  </body>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("\t  function menuToggle(){\r\n");
      out.write("\t      const toggleMenu = document.querySelector('.menu');\r\n");
      out.write("\t      toggleMenu.classList.toggle('active');\r\n");
      out.write("\t  }\r\n");
      out.write("  </script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 바디부분 시작 -->\r\n");
      out.write("\t<div class=\"mt-4\">\r\n");
      out.write("\t\t<div class=\"container d-flex justify-content-center\">\r\n");
      out.write("\t\t\t<div class=\"col-9\">\r\n");
      out.write("\t\t\t\t<!-- 선택한 값만 모여주게 할 수 있는 라디오 버튼 --> \r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"Gallery\" id=\"check1\" checked /> \r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"Gallery\" id=\"check2\" /> \r\n");
      out.write("\t\t\t\t<input type=\"radio\"\tname=\"Gallery\" id=\"check3\" />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 최상위 박스 -->\r\n");
      out.write("\t\t\t\t<div class=\"contentBox\">\r\n");
      out.write("\t\t\t\t\t<!-- 선택하는 곳 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"top-content\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"check1\">전체보기</label> \r\n");
      out.write("\t\t\t\t\t\t<label for=\"check2\">입양대기</label> \r\n");
      out.write("\t\t\t\t\t\t<label for=\"check3\">입양후기</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn\" value=\"입양 후기 글작성\" onclick=\"location.href='pet.do?command=insertform'\"/>\r\n");

						if((logindto != null) && (logindto.getMem_role().equals("ADMIN"))){

      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"btn\" value=\"크롤링해주기(입양대기)\" onclick=\"location.href='crawling.do?command=animal&mem_no=");
      out.print(logindto.getMem_no());
      out.write("&brd_no=2'\"/>\r\n");

						}

      out.write("\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 글게시물  -->\r\n");
      out.write("\t\t\t\t\t<div class=\"photo-gallery\">\r\n");
      out.write("\t\t\t\t\t\t");

							if(list == null || list.size() ==0){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1>글없음</h1>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {			
								//getBrd_no() :2 =입양 대기, :3 = 입양 후기게시판 
								//전체페이지를 불러오는 코드
								for (BoardDto dto : list){
									if(dto.getBrd_no()==2){
									
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- dto.getBrd_no()==2 일경우(입양대기)\t -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pic wait\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"resources/saveFile/");
      out.print( dto.getImage() );
      out.write("\" data-original=\"");
      out.print( dto.getImage() );
      out.write("\" articleNo=\"");
      out.print(dto.getArticle_no() );
      out.write("\" chk=\"stop\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t    \t\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\t");

									}else if(dto.getBrd_no()==3){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- dto.getBrd_no()==3 일경우(입양후기)\t -->\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pic after\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"savefile/");
      out.print( dto.getImage() );
      out.write("\" data-original=\"");
      out.print( dto.getImage() );
      out.write("\" articleNo=\"");
      out.print(dto.getArticle_no() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
				
									}
								}
							}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!--  아래 같은 형식으로 계속 출력 시킬것!-->\r\n");
      out.write("\t\t\t\t\t\t<!-- img의 chk 과 div 클래스의 pic wait 인 경우 입양대기 -->\r\n");
      out.write("\t\t\t\t\t\t<!-- div 클래스의 pic after 인 경우 입양후기 -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic wait\"> 입양 대기형식\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"resources/TestImage/dog1.jpg\" data-original=\"dog1.jpg\" chk=\"stop\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic after\"> 입양 후기 형식\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"resources/TestImage/dog4.jpg\" data-original=\"dog4.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 모달창생성 -->\r\n");
      out.write("\t<div class=\"modal1\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"full-img\">\r\n");
      out.write("\t\t\t<div class=\"modalImg\">\r\n");
      out.write("\t\t\t\t<img src=\"resources/TestImage/dog2.jpg\" alt=\"\" class=\"thisImg\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modalText\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-text-title\">\r\n");
      out.write("\t\t\t\t\t<span id=\"title\">제목</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-text-content\">\r\n");
      out.write("\t\t\t\t\t<span id=\"content\"> 내용 부분 </span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- onclick 부분 href 해주시면 됩니다. -->\r\n");
      out.write("\t\t\t\t<div class=\"wrap\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"\" id=\"TextArticleNo\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"삭제하기\" class=\"modal-button\" onclick=\"deleteData()\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"수정하기\" class=\"modal-button\" onclick=\"updateData()\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"입양신청하러가기\" class=\"modal-button\" id=\"apply\" onclick=\"applyData()\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
